version: '3'
services:

  loyalty-admin:
    build: admin_panel
    env_file: admin.env
    expose:
      - "8010"
    volumes:
      - static_volume:/opt/app/staticfiles
    depends_on:
      postgres:
        condition: service_healthy

  loyalty-api:
    build: loyalty_api
    env_file: api.env
    expose:
      - "8009"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    container_name: redis_loyalty
    image: redis:7.0.5
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  postgres:
    container_name: postgres_loyalty
    image: postgres:13
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=app
      - POSTGRES_DB=loyalty_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "auth_service_db" ]
      interval: 10s
      timeout: 30s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/var/www
    depends_on:
      - loyalty-admin
      - loyalty-api
    ports:
      - "80:80"
volumes:
  static_volume:
  redis_data:
